project:
  type: book
  
filters:
  - filters/date.lua

book:
  title: "Oltre i punteggi"
  subtitle: "Elementi di psicometria per la neuropsicologia clinica"
  author: "Giorgio Arcara"
  date: today
  search: true
  repo-url: "https://github.com/giorgioarcara/psicometria-pratica-clinica"
  repo-actions: [issue, edit]
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - chapters/Introduzione.qmd
    - chapters/Bibliografia.qmd
    - part: "Appendici"
      chapters:
      - chapters/Appendici/note-redazione.qmd
      #- chapters/Appendici/elementi-di-statistica.qmd
  #appendices:
  #  - chapters/Appendici/note-redazione.qmd
  page-navigation: true

bibliography: references.bib
csl: apa-6th-edition.csl

format:
  epub:
    toc:
      true
    lang:
      it
    date:
      "2023-10-19"
    css:
      epub.css
  html:
    include-in-header:
      file: header.html
    theme:
      light: flatly
      dark: solar
    css:
      epub.css
    lang: it   # Sets the page language
  pdf:
    keep-tex: true
    documentclass: scrbook #book
    lang: it
    citation_package: biblatex
    citeproc: false
    classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,10pt]
    include-in-header:
      text: |
        \renewcommand*{\thepart}{} % to avoid numbers in parts
        \renewcommand*{\partname}{} % to avoid label "Parte"
        \usepackage[backend=biber,style=apa]{biblatex}
        \addbibresource{references.bib}  % path corretto al tuo .bib
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \areaset[0.50in]{4.5in}{8in}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
           showspaces = false,
           showtabs = false,
           breaksymbolleft={},
           breaklines
           % Note: setting commandchars=\\\{\} here will cause an error
        }
    # include-after-body:
    #  text: |
    #    \printbibliography
    fig-pos: 'H'
